alter table artist add gender varchar2(1);
alter table song modify sng_name varchar2(100);
desc song;
alter table sungby modify recd_date date not null;
desc sungby;
alter table studio add constraint phn_unq unique(stu_phone);
insert into studio values ('A studio','chennai',1111111111);
insert into song values ('A0002',2,'FIVE',5,'NAT');
alter table song drop constraint genre_check1;
alter table song add constraint genre_chk1 check (sng_gnr in ('PHI','REL','LOV','DEV','PAT','NAT'));
insert into song values ('A0002',2,'FIVE',5,'NAT');
select * from song;
select * from sungby;
delete from song where al_id='A0001' and track_no=1;
alter table sungby drop constraint fk2;
alter table sungby add constraint fk2 foreign key (al_id,track_no) references song(al_id,track_no) on delete cascade;
delete from song where al_id='A0001' and track_no=1;
select * from song;
select * from sungby where al_id='A0001' and track_no=1;